import {
  Bot, Mail, FileText, Calendar, MessageSquare, Search,
  Zap, Shield, BarChart3, Users, Puzzle,
  GitBranch, Repeat, Clock, CircleStop, Sparkles,
  Globe, Code, Shuffle, Layers, Bell,
  Plug, Server, Webhook,
} from "lucide-react";
import { SiGithub } from "react-icons/si";

export const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  bot: Bot,
  mail: Mail,
  file: FileText,
  calendar: Calendar,
  message: MessageSquare,
  search: Search,
  zap: Zap,
  shield: Shield,
  chart: BarChart3,
  users: Users,
  puzzle: Puzzle,
  "git-branch": GitBranch,
  repeat: Repeat,
  clock: Clock,
  "circle-stop": CircleStop,
  sparkles: Sparkles,
  globe: Globe,
  code: Code,
  shuffle: Shuffle,
  layers: Layers,
  bell: Bell,
  plug: Plug,
  server: Server,
  webhook: Webhook,
  github: SiGithub as any,
};
