import { db } from "./db";
import { agents, skills, githubRepos } from "@shared/schema";
import { eq } from "drizzle-orm";

const templateData = [
  {
    name: "Email Triage Assistant",
    description: "Automatically categorize incoming emails by priority and topic, flag urgent items, and draft quick replies for common inquiries.",
    prompt: "When an email arrives in my inbox, analyze the content and sender. Categorize it as urgent, important, or low priority. For support emails, draft a polite acknowledgment. For meeting requests, check my calendar availability. Flag anything from VIP contacts.",
    icon: "mail",
    color: "#4285f4",
    triggerType: "email",
    category: "email",
    isTemplate: true,
    status: "active",
  },
  {
    name: "Meeting Notes Summarizer",
    description: "After every meeting, generate concise summaries with action items, key decisions, and follow-up tasks assigned to participants.",
    prompt: "After each meeting ends, create a structured summary including: attendees, key discussion points, decisions made, and action items with owners and deadlines. Send the summary to all participants via email and save it to the shared Drive folder.",
    icon: "calendar",
    color: "#34a853",
    triggerType: "event",
    category: "productivity",
    isTemplate: true,
    status: "active",
  },
  {
    name: "Weekly Status Reporter",
    description: "Compile project updates from team members across Sheets and Docs into a formatted weekly status report every Friday.",
    prompt: "Every Friday at 3 PM, collect updates from the project tracking sheet, recent document changes, and email threads. Compile into a clean status report with sections for each team. Highlight blockers and at-risk deliverables. Send to leadership group.",
    icon: "chart",
    color: "#fbbc04",
    triggerType: "schedule",
    category: "productivity",
    isTemplate: true,
    status: "active",
  },
  {
    name: "Customer Support Router",
    description: "Analyze support tickets, detect sentiment and urgency, then route to the right team member with context and suggested responses.",
    prompt: "When a new support ticket arrives, analyze the content for sentiment, urgency, and topic category. Route technical issues to engineering, billing questions to finance, and feature requests to product. Include a suggested response draft and relevant knowledge base articles.",
    icon: "message",
    color: "#ea4335",
    triggerType: "email",
    category: "support",
    isTemplate: true,
    status: "active",
  },
  {
    name: "HR Onboarding Coordinator",
    description: "Automate new hire onboarding by sending welcome emails, creating accounts, assigning training, and scheduling orientation meetings.",
    prompt: "When a new employee is added to the HR sheet, send a personalized welcome email with first-day instructions. Create a checklist doc from the onboarding template. Schedule orientation meetings with their manager and buddy. Set up access requests for required tools.",
    icon: "users",
    color: "#8b5cf6",
    triggerType: "event",
    category: "hr",
    isTemplate: true,
    status: "active",
  },
  {
    name: "Sales Lead Qualifier",
    description: "Score and qualify inbound leads based on company size, industry, engagement signals, and buying intent indicators.",
    prompt: "When a new lead form submission arrives, research the company online. Score the lead based on company size, industry fit, and engagement history. If score is above threshold, create a briefing doc and notify the assigned sales rep. Add to the pipeline tracker sheet.",
    icon: "zap",
    color: "#f97316",
    triggerType: "webhook",
    category: "sales",
    isTemplate: true,
    status: "active",
  },
  {
    name: "Document Review Agent",
    description: "Review documents for compliance, formatting standards, and completeness. Flag issues and suggest corrections automatically.",
    prompt: "When a document is shared for review, check for compliance with company standards: proper formatting, required sections present, no placeholder text, correct branding. Generate a review checklist with findings and suggestions. Add comments directly in the document.",
    icon: "file",
    color: "#06b6d4",
    triggerType: "event",
    category: "productivity",
    isTemplate: true,
    status: "active",
  },
  {
    name: "Security Alert Monitor",
    description: "Monitor security alerts and access logs, identify anomalies, and notify the security team with incident analysis and recommended actions.",
    prompt: "Continuously monitor access logs and security alerts. When unusual activity is detected (failed login attempts, access from new locations, privilege escalation), analyze the context and severity. Create an incident report and alert the security team via Chat with recommended immediate actions.",
    icon: "shield",
    color: "#ec4899",
    triggerType: "schedule",
    category: "data",
    isTemplate: true,
    status: "active",
  },
];

const skillsData = [
  {
    name: "ChittyScore",
    description: "6D Behavioral Trust Scoring Engine. Analyzes trust across Source, Temporal, Channel, Outcome, Network, and Justice dimensions.",
    icon: "shield",
    color: "#4285f4",
    category: "trust",
    repoUrl: "https://github.com/chittyos/chittyscore",
    repoName: "chittyscore",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Trust scoring", "Behavioral analysis", "6D evaluation", "Risk assessment"],
    status: "available",
  },
  {
    name: "ChittyVerify",
    description: "Document and identity verification service for secure authentication and compliance checks.",
    icon: "shield",
    color: "#34a853",
    category: "verification",
    repoUrl: "https://github.com/chittyos/chittyverify",
    repoName: "chittyverify",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Document verification", "Identity checks", "Compliance validation", "KYC/KYB"],
    status: "available",
  },
  {
    name: "ChittyIntel",
    description: "AI-powered case intelligence with fact extraction, contradiction detection, and timeline construction.",
    icon: "search",
    color: "#8b5cf6",
    category: "intelligence",
    repoUrl: "https://github.com/chittyos/chittyintel",
    repoName: "chittyintel",
    language: "JavaScript",
    isEcosystem: true,
    capabilities: ["Fact extraction", "Contradiction detection", "Timeline construction", "Case analysis"],
    status: "available",
  },
  {
    name: "ChittyBeacon",
    description: "Service discovery and health monitoring for distributed systems and microservices.",
    icon: "zap",
    color: "#f97316",
    category: "monitoring",
    repoUrl: "https://github.com/chittyos/chittybeacon",
    repoName: "chittybeacon",
    language: "JavaScript",
    isEcosystem: true,
    capabilities: ["Service discovery", "Health checks", "Uptime monitoring", "Alert routing"],
    status: "available",
  },
  {
    name: "ChittyMonitor",
    description: "System monitoring and performance tracking with real-time metrics and anomaly detection.",
    icon: "chart",
    color: "#ea4335",
    category: "monitoring",
    repoUrl: "https://github.com/chittyos/chittymonitor",
    repoName: "chittymonitor",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Performance tracking", "Real-time metrics", "Anomaly detection", "System health"],
    status: "available",
  },
  {
    name: "ChittyLedger",
    description: "Distributed ledger for transaction tracking with immutable audit trails and reconciliation.",
    icon: "file",
    color: "#06b6d4",
    category: "data",
    repoUrl: "https://github.com/chittyos/chittyledger",
    repoName: "chittyledger",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Transaction tracking", "Audit trails", "Reconciliation", "Ledger management"],
    status: "available",
  },
  {
    name: "ChittyChronicle",
    description: "Legal timeline management for evidentiary tracking and litigation support workflows.",
    icon: "calendar",
    color: "#ec4899",
    category: "legal",
    repoUrl: "https://github.com/chittyos/chittychronicle",
    repoName: "chittychronicle",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Timeline management", "Evidence tracking", "Litigation support", "Case management"],
    status: "available",
  },
  {
    name: "ChittyScrape",
    description: "Browser automation scraper service for data extraction and web monitoring tasks.",
    icon: "search",
    color: "#fbbc04",
    category: "automation",
    repoUrl: "https://github.com/chittyos/chittyscrape",
    repoName: "chittyscrape",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Web scraping", "Data extraction", "Browser automation", "Content monitoring"],
    status: "available",
  },
  {
    name: "ChittyMCP",
    description: "Multi-Tenant Model Context Protocol Server with OAuth, rate limiting, analytics, and 44+ tools.",
    icon: "bot",
    color: "#4285f4",
    category: "ai",
    repoUrl: "https://github.com/chittyos/chittymcp",
    repoName: "chittymcp",
    language: "JavaScript",
    isEcosystem: true,
    capabilities: ["MCP server", "Multi-tenant", "OAuth", "44+ tools", "Rate limiting"],
    status: "available",
  },
  {
    name: "ChittyRouter",
    description: "Intelligent AI routing service for multi-model gateway with automatic model selection.",
    icon: "zap",
    color: "#8b5cf6",
    category: "ai",
    repoUrl: "https://github.com/chittyos/chittyrouter",
    repoName: "chittyrouter",
    language: "JavaScript",
    isEcosystem: true,
    capabilities: ["AI routing", "Multi-model gateway", "Model selection", "Load balancing"],
    status: "available",
  },
  {
    name: "ChittyConnect",
    description: "Universal context management for user, project, and session contexts with inheritance and materialization.",
    icon: "users",
    color: "#34a853",
    category: "utility",
    repoUrl: "https://github.com/chittyos/chittyconnect",
    repoName: "chittyconnect",
    language: "JavaScript",
    isEcosystem: true,
    capabilities: ["Context management", "Session tracking", "State inheritance", "Materialization"],
    status: "available",
  },
  {
    name: "ChittyAssets",
    description: "Blockchain-integrated asset management system with ownership proof and dashboard filtering.",
    icon: "file",
    color: "#f97316",
    category: "data",
    repoUrl: "https://github.com/chittyos/chittyassets",
    repoName: "chittyassets",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Asset management", "Blockchain integration", "Ownership proof", "Dashboard filtering"],
    status: "available",
  },
  {
    name: "ChittyConcierge",
    description: "AI-powered communication orchestrator for multi-channel messaging and notification management.",
    icon: "message",
    color: "#06b6d4",
    category: "communication",
    repoUrl: "https://github.com/chittyos/chittyconcierge",
    repoName: "chittyconcierge",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Communication orchestration", "Multi-channel", "Notification management", "AI responses"],
    status: "available",
  },
  {
    name: "ChittyTrack",
    description: "Centralized observability for logs, metrics, and traces via Cloudflare Tail Workers.",
    icon: "chart",
    color: "#ea4335",
    category: "monitoring",
    repoUrl: "https://github.com/chittyos/chittytrack",
    repoName: "chittytrack",
    language: "TypeScript",
    isEcosystem: true,
    capabilities: ["Log aggregation", "Metrics collection", "Distributed tracing", "Observability"],
    status: "available",
  },
];

const chittyosRepos = [
  { name: "chittyscore", fullName: "chittyos/chittyscore", description: "6D Behavioral Trust Scoring Engine for ChittyOS", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyscore", stars: 0, forks: 0 },
  { name: "chittyverify", fullName: "chittyos/chittyverify", description: "Document and identity verification service", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyverify", stars: 0, forks: 0 },
  { name: "chittybeacon", fullName: "chittyos/chittybeacon", description: "Service discovery and health monitoring", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittybeacon", stars: 0, forks: 0 },
  { name: "chittyops", fullName: "chittyos/chittyops", description: "Standardized CI/CD workflows with ChittyBeacon integration", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittyops", stars: 0, forks: 0 },
  { name: "chittyassets", fullName: "chittyos/chittyassets", description: "Blockchain-integrated asset management system", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyassets", stars: 0, forks: 0 },
  { name: "chittyledger", fullName: "chittyos/chittyledger", description: "Distributed ledger for transaction tracking", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyledger", stars: 0, forks: 0 },
  { name: "chittymonitor", fullName: "chittyos/chittymonitor", description: "System monitoring and performance tracking", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittymonitor", stars: 0, forks: 0 },
  { name: "chittychronicle", fullName: "chittyos/chittychronicle", description: "Legal timeline management for evidentiary tracking", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittychronicle", stars: 0, forks: 0 },
  { name: "chittycore", fullName: "chittyos/chittycore", description: "Essential foundation package with ID, auth, verification, beacon tracking", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittycore", stars: 0, forks: 0 },
  { name: "chittyos-cli", fullName: "chittyos/chittyos-cli", description: "Unified CLI with AI intelligence and system integration", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittyos-cli", stars: 0, forks: 0 },
  { name: "chittygateway", fullName: "chittyos/chittygateway", description: "Unified Cloudflare Worker consolidating all services", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittygateway", stars: 0, forks: 0 },
  { name: "chittyregistry", fullName: "chittyos/chittyregistry", description: "Universal tool/script registry for ChittyOS ecosystem", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyregistry", stars: 0, forks: 0 },
  { name: "chittyrouter", fullName: "chittyos/chittyrouter", description: "Intelligent AI routing service for ChittyOS platform", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittyrouter", stars: 0, forks: 0 },
  { name: "chittyconnect", fullName: "chittyos/chittyconnect", description: "Universal context management with inheritance and materialization", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittyconnect", stars: 0, forks: 0 },
  { name: "chittymcp", fullName: "chittyos/chittymcp", description: "Multi-Tenant MCP Server with OAuth, rate limiting, 44+ tools", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittymcp", stars: 0, forks: 0 },
  { name: "chittyintel", fullName: "chittyos/chittyintel", description: "AI-powered legal fact extraction and contradiction detection", language: "JavaScript", htmlUrl: "https://github.com/chittyos/chittyintel", stars: 0, forks: 0 },
  { name: "chittyscrape", fullName: "chittyos/chittyscrape", description: "Browser automation scraper service", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyscrape", stars: 0, forks: 0 },
  { name: "chittyconcierge", fullName: "chittyos/chittyconcierge", description: "AI-powered communication orchestrator", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittyconcierge", stars: 0, forks: 0 },
  { name: "chittycommand", fullName: "chittyos/chittycommand", description: "Unified life management & action dashboard", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittycommand", stars: 0, forks: 0 },
  { name: "chittytrack", fullName: "chittyos/chittytrack", description: "Centralized observability via Cloudflare Tail Workers", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittytrack", stars: 0, forks: 0 },
  { name: "get-chitty", fullName: "chittyos/get-chitty", description: "ChittyOS multi-model AI gateway", language: "TypeScript", htmlUrl: "https://github.com/chittyos/get-chitty", stars: 0, forks: 0 },
  { name: "chittycan", fullName: "chittyos/chittycan", description: "Autonomous network with natural language commands and DNA vaults", language: "TypeScript", htmlUrl: "https://github.com/chittyos/chittycan", stars: 0, forks: 0 },
  { name: "sessionsync", fullName: "chittyos/sessionsync", description: "Self-evolving AI cross-session coordination system", language: "TypeScript", htmlUrl: "https://github.com/chittyos/sessionsync", stars: 0, forks: 0 },
  { name: "shared", fullName: "chittyos/shared", description: "Consolidated shared dependencies for all ChittyOS components", language: "TypeScript", htmlUrl: "https://github.com/chittyos/shared", stars: 0, forks: 0 },
  { name: "docs", fullName: "chittyos/docs", description: "Official docs and guides for the legal technology ecosystem", language: "HTML", htmlUrl: "https://github.com/chittyos/docs", stars: 0, forks: 0 },
];

export async function seedDatabase() {
  try {
    const existingTemplates = await db.select().from(agents).where(eq(agents.isTemplate, true));
    if (existingTemplates.length === 0) {
      for (const template of templateData) {
        await db.insert(agents).values({
          ...template,
          triggerConfig: {},
          actions: [],
          skillIds: [],
        });
      }
      console.log(`Seeded ${templateData.length} templates`);
    }

    const existingSkills = await db.select().from(skills);
    if (existingSkills.length === 0) {
      for (const skill of skillsData) {
        await db.insert(skills).values(skill);
      }
      console.log(`Seeded ${skillsData.length} skills`);
    }

    const existingRepos = await db.select().from(githubRepos);
    if (existingRepos.length === 0) {
      for (const repo of chittyosRepos) {
        await db.insert(githubRepos).values(repo);
      }
      console.log(`Seeded ${chittyosRepos.length} GitHub repos`);
    }
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
